"use strict";
let users;
users = [];
let user1;
user1 = { userName: "John Doe", userId: 1 };
users.push(user1);
let user2;
user2 = { userName: "Michael", userId: 2 };
users.push(user2);
console.log(users);
